#ifndef PLUGINTEMPLATE_GLOBAL_H
#define PLUGINTEMPLATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINTEMPLATE_LIBRARY)
#  define PLUGINTEMPLATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINTEMPLATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINTEMPLATE_GLOBAL_H
