// This file was generated by qlalr - DO NOT EDIT!
#ifndef DARLANGPARSER_P_H
#define DARLANGPARSER_P_H

class DarlangParser
{
public:
  enum VariousConstants {
    EOF_SYMBOL = 0,
    T_AND = 35,
    T_ANDAND = 36,
    T_COMMA = 27,
    T_DIV = 19,
    T_DOT = 28,
    T_EQ = 30,
    T_FALSE = 12,
    T_IDENTIFIER = 39,
    T_LBRACKET = 24,
    T_LCURLYBRACE = 22,
    T_LESS = 32,
    T_LESS_EQ = 34,
    T_LPAREN = 20,
    T_MINUS = 16,
    T_MINUSMINUS = 17,
    T_MORE = 31,
    T_MORE_EQ = 33,
    T_NUMBER_INTEGER = 41,
    T_NUMBER_REAL = 42,
    T_OR = 37,
    T_OROR = 38,
    T_PLUS = 14,
    T_PLUSPLUS = 15,
    T_QUOTE = 26,
    T_RBRACKET = 25,
    T_RCURLYBRACE = 23,
    T_RPAREN = 21,
    T_SEMICOLON = 29,
    T_STAR = 18,
    T_STRING_LITERAL = 40,
    T_TRUE = 13,
    TypeBOOL = 9,
    TypeBYTE = 8,
    TypeDOUBLE = 5,
    TypeFLOAT = 6,
    TypeINT = 1,
    TypeINT64 = 3,
    TypeOBJECT = 10,
    TypeSTRING = 7,
    TypeUINT = 2,
    TypeUINT64 = 4,
    TypeVOID = 11,

    ACCEPT_STATE = 21,
    RULE_COUNT = 38,
    STATE_COUNT = 57,
    TERMINAL_COUNT = 43,
    NON_TERMINAL_COUNT = 15,

    GOTO_INDEX_OFFSET = 57,
    GOTO_INFO_OFFSET = 155,
    GOTO_CHECK_OFFSET = 155
  };

  static const char  *const    spell [];
  static const short             lhs [];
  static const short             rhs [];

#ifndef QLALR_NO_DARLANGPARSER_DEBUG_INFO
  static const int     rule_index [];
  static const int      rule_info [];
#endif // QLALR_NO_DARLANGPARSER_DEBUG_INFO

  static const short    goto_default [];
  static const short  action_default [];
  static const short    action_index [];
  static const short     action_info [];
  static const short    action_check [];

  static inline int nt_action (int state, int nt)
  {
    const int yyn = action_index [GOTO_INDEX_OFFSET + state] + nt;
    if (yyn < 0 || action_check [GOTO_CHECK_OFFSET + yyn] != nt)
      return goto_default [nt];

    return action_info [GOTO_INFO_OFFSET + yyn];
  }

  static inline int t_action (int state, int token)
  {
    const int yyn = action_index [state] + token;

    if (yyn < 0 || action_check [yyn] != token)
      return - action_default [state];

    return action_info [yyn];
  }
};


#endif // DARLANGPARSER_P_H

