#ifndef SPECTRUMBANDFACTORY_GLOBAL_H
#define SPECTRUMBANDFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPECTRUMBANDFACTORY_LIBRARY)
#  define SPECTRUMBANDFACTORY_EXPORT Q_DECL_EXPORT
#else
#  define SPECTRUMBANDFACTORY_EXPORT Q_DECL_IMPORT
#endif

#endif // SPECTRUMBANDFACTORY_GLOBAL_H
